[package]
name = "bundlr-sdk"
description = "Bundlr Network Rust sdk"
homepage = "https://bundlr.network"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/Bundlr-Network/rust-sdk"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.56"
async-recursion = "0.3.2"
async-stream = "0.3"
avro-rs = "0.13.0"
bs58 = "0.4.0"
bytes = "1.1"
data-encoding = "2.2.0"
derive_builder = "0.9"
derive_more = "0.99.3"
ed25519-dalek = { version = "1.0.1", optional = true }
futures = "0.3.13"
jsonwebkey = { version = "0.3.2", features = [ "pkcs-convert" ] }
lazy_static = "1.4.0"
num-derive = "0.3.3"
num-traits = "0.2"
pipe = "0.2"
primitive-types = "0.11.1"
rand = "0.8"
reqwest = "0.11.11"
ring = "0.16.20"
rsa = "0.5"
secp256k1 = { version = "0.21.3", optional = true, features = [ "recovery" ] }
serde = "1.0.136"
serde_json = "1.0.79"
sha2 = "0.10"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = [ "fs" ]}
tokio-util = "0.6"
web3 = { version = "0.18.0", optional = true }

[dev-dependencies]
tokio-test = "0.4.2"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[features]
default = ["solana", "ethereum", "erc20", "cosmos"]
cosmos = ["secp256k1"]
erc20 = ["secp256k1", "web3"]
ethereum = ["secp256k1", "web3"]
solana = ["ed25519-dalek"]
